name = "fukaibox"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# OpenNext用のワーカー設定
main = ".open-next/worker.js"

# アセット設定
[assets]
directory = ".open-next/assets"
binding = "ASSETS"
